"""create parties shipments documents tables

Revision ID: 56b789305416
Revises: 
Create Date: 2026-03-17 21:45:22.423651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56b789305416'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('importer', 'exporter', 'agent', 'customs_broker', 'freight_forwarder', name='party_role'), nullable=False),
    sa.Column('tax_pin', sa.String(length=40), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('ref_number', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_transit', 'at_customs', 'customs_cleared', 'delivered', 'on_hold', name='shipment_status'), nullable=False),
    sa.Column('direction', sa.Enum('import_', 'export', name='shipment_direction'), nullable=False),
    sa.Column('origin_country', sa.String(length=60), nullable=False),
    sa.Column('origin_port', sa.String(length=80), nullable=True),
    sa.Column('destination_country', sa.String(length=60), nullable=False),
    sa.Column('destination_port', sa.String(length=80), nullable=True),
    sa.Column('incoterms', sa.Enum('EXW', 'FOB', 'CIF', 'CFR', 'DAP', 'DDP', name='incoterms_code'), nullable=True),
    sa.Column('commodity', sa.String(length=255), nullable=True),
    sa.Column('hs_code', sa.String(length=20), nullable=True),
    sa.Column('gross_weight_kg', sa.Float(), nullable=True),
    sa.Column('volume_cbm', sa.Float(), nullable=True),
    sa.Column('etd', sa.Date(), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('ata', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('shipper_id', sa.UUID(), nullable=False),
    sa.Column('consignee_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consignee_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['shipper_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_number')
    )
    op.create_table('documents',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('bill_of_lading', 'airway_bill', 'commercial_invoice', 'packing_list', 'certificate_of_origin', 'customs_entry', 'phytosanitary', 'insurance_certificate', 'other', name='document_type'), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'parsing', 'parsed', 'verified', 'rejected', name='document_status'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('shipments')
    op.drop_table('parties')
    # ### end Alembic commands ###
